#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import sys,os
try:
    if sys.argv[1]=='push':
        os.system("cp -f data/* /usr/share/games/fortunes/")
    elif sys.argv[1]=='pull':
        os.system("cp -f /usr/share/games/fortunes/* data")
    else:
        print("Usage: update [push] [pull]")
except:
    print("Usage: update [push] [pull]")
